
apiVersion: v1
kind: Service
metadata:
  name: sprint-poc
  labels:
    app: sprint-poc
spec:
  ports:
    ports:
  - name: liberty
    protocol: TCP
    port: 9080
    targetPort: 9080
  - name: tomcat
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: sprint-poc
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sprint-poc
  name: sprint-poc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sprint-poc
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
          protocol: TCP
      - image: webcenter/activemq
        name: activemq
        ports:
        - containerPort: 61613
          protocol: TCP
      - image: mycluster.icp:8500/default/sprintpoc:latest
        name: sprint-poc
        ports:
        - containerPort: 9080
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
