
apiVersion: v1
kind: Service
metadata:
  name: sprint-poc
  labels:
    app: sprint-poc
spec:
  ports:
    ports:
  - name: liberty
    protocol: TCP
    port: 9080
    targetPort: 9080
  - name: tomcat
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: sprint-poc
  type: NodePort

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sprint-poc
  labels:
    chart: sprint-poc
data:
  application.properies: /
    spring.activemq.broker-url=tcp://localhost:61616
    spring.activemq.user=admin
    spring.activemq.password=admin
    spring.data.mongodb.host=order-mongodb-ibm-mongodb-dev.sprint.svc.cluster.local
    spring.data.mongodb.port=32599
    spring.data.mongodb.database=orders
    spring.data.mongodb.username=mongo
    spring.data.mongodb.password=passw0rd

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sprint-poc
  name: sprint-poc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sprint-poc
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
          protocol: TCP
      - image: webcenter/activemq
        name: activemq
        ports:
        - containerPort: 61613
          protocol: TCP
      - image: mycluster.icp:8500/default/sprintpoc:latest
        name: sprint-poc
        ports:
        - containerPort: 9080
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
          - name: config
            mountPath: application.properties
        resources:
          volumes:
            - name: config
            configMap:
              name: sprint-poc
